// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn7_YaDUUlNyJXyCA7lhcZbOlZ9oNzOAM',
    appId: '1:693004144126:web:66b530067ce4eb1e3984af',
    messagingSenderId: '693004144126',
    projectId: 'capstone-74357',
    authDomain: 'capstone-74357.firebaseapp.com',
    storageBucket: 'capstone-74357.appspot.com',
    measurementId: 'G-ZN33JBDLBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm4uskEkyqbKT1Tb75gHoDcnrUATjKyoc',
    appId: '1:693004144126:android:9934df84de0eb15b3984af',
    messagingSenderId: '693004144126',
    projectId: 'capstone-74357',
    storageBucket: 'capstone-74357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXzj5YV91dejOhQFJOgumuaDX36AaYTBo',
    appId: '1:693004144126:ios:82c9549806ff9a373984af',
    messagingSenderId: '693004144126',
    projectId: 'capstone-74357',
    storageBucket: 'capstone-74357.appspot.com',
    iosClientId: '693004144126-t7hjq2vpti5nhps8a6jollbndgja5a31.apps.googleusercontent.com',
    iosBundleId: 'com.edureka.tcs.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXzj5YV91dejOhQFJOgumuaDX36AaYTBo',
    appId: '1:693004144126:ios:15dfc4c338878c863984af',
    messagingSenderId: '693004144126',
    projectId: 'capstone-74357',
    storageBucket: 'capstone-74357.appspot.com',
    iosClientId: '693004144126-tah6gm2c1ifpotktb76ccten4gmrce5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstone.RunnerTests',
  );
}
